meta_product_name: "Mokey"
meta_title: "Mokey.ca | Download Food & eat differently."
meta_description: "Relevant description"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
